trigger:
  - main

pool:
  name: 'k8s-test-pool'

variables:
  imageRepository: 'k8s-agent-test'
  containerRegistry: 'hedeffilo-acr-conn'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

steps:
- script: |
    echo "Running on agent: $(Agent.Name)"
    echo "Testing Docker Daemon connection via DinD..."
    docker version
  displayName: 'Verify Environment & Docker Connectivity'

- task: Docker@2
  displayName: 'Build and Push to ACR'
  inputs:
    command: 'buildAndPush'
    containerRegistry: '$(containerRegistry)'
    repository: '$(imageRepository)'
    dockerfile: '$(dockerfilePath)'
    tags: |
      $(tag)
      latest